# Generated by Django 5.2.7 on 2025-10-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('weight', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_space', models.PositiveBigIntegerField(default=0)),
                ('active_status', models.BooleanField(default=True)),
                ('release_update_status', models.BooleanField(default=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
